// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Camera: typeof import('./src/components/camera/index.vue')['default']
    Container: typeof import('./src/components/container/index.vue')['default']
    DatePicker: typeof import('./src/components/date-picker/index.vue')['default']
    Dot: typeof import('./src/components/dot/index.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    InteractiveSessionSteps: typeof import('./src/components/interactive-session-steps/index.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCalendar: typeof import('@nutui/nutui-taro')['Calendar']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutCheckboxGroup: typeof import('@nutui/nutui-taro')['CheckboxGroup']
    NutDatePicker: typeof import('@nutui/nutui-taro')['DatePicker']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutForm: typeof import('@nutui/nutui-taro')['Form']
    NutFormItem: typeof import('@nutui/nutui-taro')['FormItem']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutPagination: typeof import('@nutui/nutui-taro')['Pagination']
    NutPicker: typeof import('@nutui/nutui-taro')['Picker']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutProgress: typeof import('@nutui/nutui-taro')['Progress']
    NutRadio: typeof import('@nutui/nutui-taro')['Radio']
    NutRadioGroup: typeof import('@nutui/nutui-taro')['RadioGroup']
    NutRate: typeof import('@nutui/nutui-taro')['Rate']
    NutStep: typeof import('@nutui/nutui-taro')['Step']
    NutSteps: typeof import('@nutui/nutui-taro')['Steps']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutTextarea: typeof import('@nutui/nutui-taro')['Textarea']
    Select: typeof import('./src/components/select/index.vue')['default']
    TabItem: typeof import('./src/components/tab-item/index.vue')['default']
  }
}
